### ISSUE TITLE
Subscriber bug 

### ISSUE THREAD

**Issue by typemytype** [jenskutilek/Curve-Equalizer#10] opened 2021-10-30 14:48 UTC
See traceback: https://forum.robofont.com/topic/993/curve-equaliser-extension-not-working-on-rf4

I didnt check it out, can have a look next week

cc @roberto-arista

**Comment by jenskutilek** [comment] 2021-11-10 09:23
Hm, cannot reproduce ...

**Comment by supertype-de** [comment] 2021-11-30 13:57
I get a traceback when launching the latest version 2.0.2 in either the latest Version 4.1 (build 2111241049) or the Beta build 2111191909

`Traceback (most recent call last):
  File "EqualizeCurves.py", line 472, in <module>
  File "/Applications/RoboFont4/RoboFont4.app/Contents/Resources/lib/python3.7/mojo/subscriber.py", line 1429, in __init__
  File "EqualizeCurves.py", line 100, in build
  File "EqualizeCurves.py", line 68, in restore_state
KeyError: -1`

I'm running RoboFont on MacOS 12.0.1 on a MacBook Pro (M1 Max)

**Comment by typemytype** [comment] 2021-11-30 15:15
`yourRadioGroup.get()` is `-1` if no radio button is checked

```python
import vanilla


def changeMethod(sender):
    print(sender.get())
        
w = vanilla.Window((400, 400))
w.r = vanilla.RadioGroup(
    (16, 10, -10, 50), 
    titles=["foo", "bar"],
    callback=changeMethod
)
# w.r.set(0)
w.open()

print(w.r.get())
```

**Comment by supertype-de** [comment] 2021-12-01 10:29
I should have written “when I try launching”, the extension does not load.

I'm not sure, is the @typemytype comment for me or @jenskutilek ?

**Comment by typemytype** [comment] 2021-12-03 21:10
only one line has to be added: `self.paletteView.group.eqMethodSelector.set(0)`

see the example https://vanilla.robotools.dev/en/latest/objects/RadioGroup.html#module-vanilla

**Comment by jenskutilek** [comment] 2021-12-04 14:24
Thanks! Should be fixed in f5e54630a8747f2d8292d5016862561247f4f699. @supertype-de you can update through Mechanic.

**Closed by jenskutilek** 2021-12-04 14:24 UTC

**Comment by supertype-de** [comment] 2021-12-06 13:54
@jenskutilek , thank you.

There seems to be a difference in the UI, the slider types of “Hobby” and “Adjust” seem to be exchanged.

<img width="200" alt="Screenshot 2021-12-06 at 14 40 19" src="https://user-images.githubusercontent.com/11456294/144856540-fee0b1fd-0ff6-4d7c-8a10-212855d8b4c2.png">

Is this change intentional? I did like the way one could use predefined slider positions (1, 2, 3, 4 or 5) for “Adjust” and then apply the same setting to other curves.

**Comment by jenskutilek** [comment] 2022-10-15 13:25
@supertype-de I finally brought back the old equalizer options in v2.1.3.

**Comment by supertype-de** [comment] 2022-10-15 14:07
🤩(sent from mobile device)On 15. Oct 2022, at 15:26, Jens Kutilek ***@***.***> wrote:﻿
@supertype-de I finally brought back the old equalizer options in v2.1.3.

**Comment by supertype-de** [comment] 2022-10-15 17:38
Klingt gut! Werde ich gleich mal ausprobieren.

Danke!
Jürgen
